### PR TITLE
once a run completes perfectly on a server, wait for a github change

### PR DESCRIPTION
**Pull request by ajdamico**
intention:

IF the run was perfect AND the github SHA-ID did not change
THEN wait 60 seconds and check SHA-ID again

@hannesmuehleisen could you check if you like this idea?  once sisyphus has a perfect run on one of the servers, it's a waste of hardware/electricity to run the exact same tests on the exact same computer with the exact same monetdblite commit, i think?  but no problem if you reject.  

if you like it, please also check if i did it properly?  i don't know bash scripting very well.

trying to show our greek god some mercy

### CODE REVIEW

**Comment by ajdamico** [comment]
@hannesmuehleisen i am not sure if added lines 14-16 are in the correct place, or if they would belong inside the `while : do` loop..

**Comment by hannes** [comment]
what about third party package updates or brazilian ftp servers acting up? I think we should just run this forever.

**Comment by ajdamico** [comment]
you could have it sleep for max of one week?  but no argument from me.
 pretty cool bash coding though, huh? ;)

**Comment by hannes** [comment]
cool coding yes :) its more of an academic issue though, and we can still hide subsequent perfect runs in ui (should those ever happen)

**Pull request closed without merging**
